version: '3'
services:
    web:
        build: ./src
        ports:
            - 8000:8000
        depends_on:
            - redis
    redis:
        image: redis
        command: redis-server --appendonly yes
        volumes:
            - redis_data:/data

volumes:
    redis_data: